version: '2'
services:
  kafka:
    build: .
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 128.130.56.90
      KAFKA_CREATE_TOPICS: "jsonSyslog:1:1"
      KAFKA_ZOOKEEPER_CONNECT: 128.130.56.90:2181
      KAFKA_BROKER_ID:0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
